source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
 
use_frameworks!

target 'ReactorCollectionViewDemo' do

  # Architecture
  pod 'ReactorKit', '0.6.0'
  pod 'Alamofire', '4.5.0'

  # Rx
  pod 'RxSwift', '3.6.1'
  pod 'RxCocoa', '3.6.1'
  pod 'RxDataSources', '1.0.4'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'RxSwift'
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
